### ISSUE TITLE
Look the screen

### ISSUE THREAD

**Issue by enzofrnt** [Ar4ys/SaveToRedux#1]
![image](https://user-images.githubusercontent.com/63660254/99188892-a2ff9500-275e-11eb-8fdc-c45659176bd2.png)

**Comment by Ar4ys** [comment]
I don`t know, how did you find this repo. This project is not done yet, and its my "learning" project (i try to refactor this plugin). I dont maintain this plugins. If you wanna use this plugins, [here](https://github.com/1Lighty/BetterDiscordPlugins) you can find them.
